spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_system?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: '045057'   # ← 这里必须是你刚才命令行登录成功的密码！
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # 不要配置 database-platform！让 Hibernate 自动识别
  # Swagger 配置（Springdoc）
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /v3/api-docs